server:
  port: 8081

spring:
  ai:
    mcp:
      server:
        name: order-service
        version: 1.0.1
        type: sync
        stdio: true
        enabled: true
        sse-endpoint: /sse
    ollama:
      chat:
        model: llama3.2:latest